Fix Cloudformation

diff --git a/main.yml b/main.yml
--- a/main.yml
+++ b/main.yml
@@ -4,29 +4,34 @@ Parameters:
   EC2InstanceType:
     Type: String
   EC2AMI:
-    Type: "AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>"
-    Default: "/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2"
+    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
+    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
   CodePipelineBucket:
     Type: String
-    Description: "The S3 bucket for CodePipeline artifacts"
+    Description: 'The S3 bucket for CodePipeline artifacts.'
   GitHubOwner:
     Type: String
-    Description: "The username of the source GitHub repo"
+    Description: 'The username of the source GitHub repo.'
   GitHubRepo:
     Type: String
-    Description: "The source GitHub repo name (without the username)"
+    Description: 'The source GitHub repo name (without the username).'
   GitHubBranch:
     Type: String
-    Description: "The source GitHub branch"
+    Default: master
+    Description: 'The source GitHub branch.'
   GitHubPersonalAccessToken:
     Type: String
-    Description: 'The GitHub personal access token with "repo" and "admin:repo_hook" permissions'
+    NoEcho: true
+    Description: 'A GitHub personal access token with "repo" and
+"admin:repo_hook" permissions.'
+
 
 Resources:
+
   SecurityGroup:
-    Type: AWS::EC2::SecurityGroup
+    Type: "AWS::EC2::SecurityGroup"
     Properties:
-      GroupDescription: !Sub "Internal Security group for ${AWS::StackName}}"
+      GroupDescription: !Sub 'Internal Security group for ${AWS::StackName}'
       SecurityGroupIngress:
         - IpProtocol: tcp
           FromPort: 8080
@@ -39,7 +44,6 @@ Resources:
       Tags:
         - Key: Name
           Value: !Ref AWS::StackName
-
   InstanceRole:
     Type: "AWS::IAM::Role"
     Properties:
@@ -57,82 +61,6 @@ Resources:
       Tags:
         - Key: Name
           Value: !Ref AWS::StackName
-
-  InstanceProfile:
-    Type: "AWS::IAM::InstanceProfile"
-    Properties:
-      Roles:
-        - Ref: InstanceRole
-
-  Instance:
-    Type: AWS::EC2::Instance
-    CreationPolicy:
-      ResourceSignal:
-        Timeout: PT15M
-        Count: 1
-    Metadata:
-      AWS::CloudFormation::Init:
-        config:
-          packages:
-            yum:
-              ruby: []
-            files:
-              /home/ec2-user/install:
-                source: !Sub "https://aws-codedeploy-${AWS::Region}.s3.amazonaws.com/latest/install"
-                mode: "000755" #executable
-            commands:
-              00-install-cd-agent:
-                command: "./install auto"
-                cwd: "/home/ec2-user/"
-    Properties:
-      ImageId: !Ref EC2AMI
-      InstanceType: !Ref EC2InstanceType
-      IamInstanceProfile: !Ref InstanceProfile
-      Monitoring: true
-      SecurityGroupIds:
-        - !GetAtt SecurityGroup.GroupId
-      UserData:
-        Fn::Base64: !Sub |
-          #!/bin/bash -xe
-
-          # Send script output to /tmp so we can debug boot failures
-          exec > /tmp/userdata.log 2>&1
-
-          # Update all packages
-          yum -y update
-
-          # Get latest cfn scripts
-          yum install -y aws-cfn-bootstrap
-
-          # Have CloudFormation install any files and packages from the metadata
-          /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --region ${AWS::Region} --resource Instance
-
-          cat > /tmp/install_script.sh << EOF
-            # START
-            echo "Setting up NodeJS Environment"
-            curl https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
-
-            # Dot source the files to ensure that variables are available within the current shell
-            . /home/ec2-user/.nvm/nvm.sh
-            . /home/ec2-user/.bashrc
-
-            # Install NVM, NPM, Node.JS
-            nvm alias default v12.7.0
-            nvm install v12.7.0
-            nvm use v12.7.0
-
-            # Create log directory
-            mkdir -p /home/ec2-user/app/log
-          EOF
-
-          chown ec2-user:ec2-user /tmp/install_script.sh && chmod a+x /tmp/install_script.sh
-          sleep 1; su - ec2-user -c "/tmp/install_script.sh"
-
-          # Signal to CloudFormation that the instance is ready
-          /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --region ${AWS::Region} --resource Instance
-      Tags:
-        - Key: Name
-          Value: !Ref AWS::StackName
   DeploymentRole:
     Type: AWS::IAM::Role
     Properties:
@@ -146,8 +74,8 @@ Resources:
               - codedeploy.amazonaws.com
               - codebuild.amazonaws.com
           Action: sts:AssumeRole
-        ManagedPolicyArns:
-          - arn:aws:iam::aws:policy/PowerUserAccess
+      ManagedPolicyArns:
+        - arn:aws:iam::aws:policy/PowerUserAccess
   BuildProject:
     Type: AWS::CodeBuild::Project
     Properties:
@@ -233,7 +161,6 @@ Resources:
                 ApplicationName: !Ref DeploymentApplication
                 DeploymentGroupName: !Ref StagingDeploymentGroup
               RunOrder: 1
-
   PipelineWebhook:
     Type: AWS::CodePipeline::Webhook
     Properties:
@@ -242,15 +169,102 @@ Resources:
         SecretToken: !Ref GitHubPersonalAccessToken
       Filters:
         - JsonPath: $.ref
-          MatchEquals: "refs/heads/{Branch}"
+          MatchEquals: 'refs/heads/{Branch}'
       TargetPipeline: !Ref Pipeline
       TargetAction: Source
-      Name: !Sub "webhook-${AWS::StackName}"
+      Name: !Sub 'webhook-${AWS::StackName}'
       TargetPipelineVersion: !GetAtt Pipeline.Version
       RegisterWithThirdParty: true
+  InstanceProfile:
+    Type: "AWS::IAM::InstanceProfile"
+    Properties:
+      Roles:
+        - Ref: InstanceRole
+  Instance:
+    Type: AWS::EC2::Instance
+    CreationPolicy: 
+      ResourceSignal:
+        Timeout: PT15M
+        Count: 1
+    Metadata:
+      AWS::CloudFormation::Init:
+        config:
+          packages: 
+            yum:
+             ruby: []
+              #wget: []
+              #unzip: []
+          files:
+            /home/ec2-user/install:
+              source: !Sub "https://aws-codedeploy-${AWS::Region}.s3.amazonaws.com/latest/install"
+              mode: "000755" # executable
+          commands:
+            00-install-cd-agent:
+              command: "./install auto"
+              cwd: "/home/ec2-user/"
+    Properties:
+      ImageId: !Ref EC2AMI
+      InstanceType: !Ref EC2InstanceType
+      IamInstanceProfile: !Ref InstanceProfile
+      Monitoring: true
+      SecurityGroupIds:
+        - !GetAtt SecurityGroup.GroupId 
+      UserData:
+        Fn::Base64: !Sub |
+          #!/bin/bash -xe
+
+          # send script output to /tmp so we can debug boot failures
+          exec > /tmp/userdata.log 2>&1 
+
+          # Update all packages
+          yum -y update
+
+          # Get latest cfn scripts; https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/best-practices.html#cfninit
+          yum install -y aws-cfn-bootstrap
+
+          cat > /tmp/install_script.sh << EOF 
+            # START
+            echo "Setting up NodeJS Environment"
+            curl https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
+
+            # Dot source the files to ensure that variables are available within the current shell
+            . /home/ec2-user/.nvm/nvm.sh
+            . /home/ec2-user/.bashrc
+
+            # Install NVM, NPM, Node.JS
+            nvm alias default v12.7.0
+            nvm install v12.7.0
+            nvm use v12.7.0
+
+            # Download latest code, unzip it into /home/ec2-user/app
+            #wget https://github.com/{{username}}/aws-bootstrap/archive/master.zip 
+            #unzip master.zip
+            #mv aws-bootstrap-master app
+
+            # Create log directory
+            mkdir -p /home/ec2-user/app/logs
+
+            # Run server
+            #cd app
+            #npm install
+            #npm start
+          EOF
+
+          chown ec2-user:ec2-user /tmp/install_script.sh && chmod a+x /tmp/install_script.sh
+          sleep 1; sudo su - ec2-user -c "/tmp/install_script.sh" 
+
+          # Have CloudFormation install any files and packages from the metadata
+          /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --region ${AWS::Region} --resource Instance
+          # Signal to CloudFormation that the instance is ready
+          /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --region ${AWS::Region} --resource Instance 
+          
+      Tags:
+        - Key: Name
+          Value: !Ref AWS::StackName
+
 Outputs:
-  InstanceDNS:
+  InstanceEndpoint:
     Description: The DNS name for the created instance
-    Value: !Sub "http://${Instance.PublicDnsName}:8080"
+    Value: !Sub "http://${Instance.PublicDnsName}:8080" 
     Export:
-      Name: InstanceDNS
+      Name: InstanceEndpoint
